package allowance

import com.me.drl.demo.allowance.TravelDetail
import com.me.drl.demo.allowance.Standard
import com.me.drl.demo.allowance.TotalAllowance
import java.math.BigDecimal
import org.joda.time.DateTime;

rule "init total allowance"
when
then
	insert(new TotalAllowance());
end

rule "daily allowance with weekend standard on weekend"
dialect "mvel"
no-loop true
when
	$total: TotalAllowance()
	$td: TravelDetail()
	$es: Standard(weekend == true, unify == false)
	$res: Double() from accumulate (
		DateTime($dw: getDayOfWeek()) from $td.days,
		init(Double $s = 0;),
		action(
			if($dw < 6) {
				$s += $es.standardAmount;
			} else {
				$s += $es.exceptionAmount;
			}
		),
		result($s)
	)
then
	modify($total) {
		setTotal($res),
		setAllowance($res - $td.amount.doubleValue())
	}
	System.out.println("lalala");
end